In [1]:
import pandas as pd
import sklearn

In [2]:
close_prices = pd.read_csv('data/close_prices.csv')

In [3]:
close_prices.head()

date        AXP          BA        CAT       CSCO         CVX  \
0  2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1  2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2  2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
3  2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
4  2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

          DD        DIS         GE          GS    ...            PFE  \
0  59.409999  64.750000  24.280001  165.250000    ...      28.799999   
1  59.319997  64.320000  24.320000  162.970001    ...      28.709999   
2  59.319997  64.449997  24.230000  162.309998    ...      28.490000   
3  59.509996  65.239998  24.250000  162.289993    ...      28.520000   
4  59.009995  65.190002  24.049999  159.850006    ...      28.879999   

          PG          T        TRV        UNH         UTX           V  \
0  79.279999  34.220001  86.379997  71.820000  109.419998  196.240005   
1  78.620003  34.090000  85.870003  72.320000  110.000000  193.339996   
2  77.720001  34.049999  85.980003  71.980003  109.260002  191.559998   
3  78.050003  34.230000  85.830002  72.160004  109.660004  193.559998   
4  77.209999  33.980000  85.410004  71.989998  109.360001  193.050003   

          VZ        WMT        XOM  
0  47.980000  76.419998  87.750000  
1  47.270000  75.750000  87.360001  
2  46.950001  74.650002  87.139999  
3  47.669998  74.620003  87.070000  
4  47.000000  74.360001  86.900002  

[5 rows x 31 columns]

In [4]:
from sklearn.decomposition import PCA

In [5]:
pca = PCA(n_components=10)

In [6]:
del close_prices['date']

array([[  76.440002,  117.510002,   85.029999, ...,   47.98    ,
          76.419998,   87.75    ],
       [  76.07    ,  119.      ,   85.110001, ...,   47.27    ,
          75.75    ,   87.360001],
       [  75.989998,  118.510002,   84.5     , ...,   46.950001,
          74.650002,   87.139999],
       ..., 
       [  81.5     ,  153.669998,   79.970001, ...,   49.27    ,
          83.290001,   84.760002],
       [  81.059998,  154.509995,   78.449997, ...,   48.950001,
          82.620003,   84.080002],
       [  81.860001,  155.729996,   81.330002, ...,   49.540001,
          82.529999,   86.07    ]])

In [10]:
pca.fit(close_prices.as_matrix())

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [11]:
pca.explained_variance_ratio_

array([ 0.73897118,  0.11007169,  0.04995088,  0.0287492 ,  0.02215448,
        0.01931577,  0.00674853,  0.00614091,  0.00320594,  0.00305611])

# task 1

In [15]:
import numpy as np

np.cumsum(pca.explained_variance_ratio_)

In [17]:
with open('t02-pca-1.txt', 'w') as fd:
    fd.write('4')

# task 2

In [23]:
res = pca.transform(close_prices)
res.shape

(374, 10)

In [25]:
len(res[:,0])

374

In [31]:
first_comp = res[:,0]

In [33]:
dji = pd.read_csv('data/djia_index.csv')
dji = dji['^DJI']

In [34]:
np.corrcoef(first_comp, dji)

array([[ 1.        ,  0.90965222],
       [ 0.90965222,  1.        ]])

In [37]:
cc = np.corrcoef(first_comp, dji)[0][1]
ans = '{:.2f}'.format(round(cc, 2))
ans

'0.91'

In [38]:
with open('t02-pca-2.txt', 'w') as fd:
    fd.write(ans)

# task 3

In [40]:
pca.components_.shape

(10, 30)

In [44]:
np.argmax(pca.components_[0])

26

In [52]:
list(close_prices.columns)[26]

'V'

In [53]:
ans = list(close_prices.columns)[np.argmax(pca.components_[0])]

In [54]:
ans

'V'

In [55]:
with open('t03-pca-3.txt', 'w') as fd:
    fd.write(ans)